#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         SPOPS
version:      0.81
version_from: SPOPS.pm
installdirs:  site
requires:
    Time::Piece:                   1.07
    Devel::StackTrace:             0.9
    Class::Accessor:               0.17
    Class::Fields:                 0.14
    Carp::Assert:                  0.17
    Storable:                      1
    Class::ISA:                    0.32
    Test::More:                    0.41
    Class::Factory:                1
    Log::Dispatch:                 2
    Log::Log4perl:                 0.35
    Class::Date:                   1
    Data::Dumper:                  2

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.12
