#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         SPOPS
version:      0.85
version_from: SPOPS.pm
installdirs:  site
requires:
    Class::ISA:                    0.32
    Storable:                      1
    Class::Fields:                 0.14
    Class::Factory:                1
    Log::Log4perl:                 0.35
    Class::Date:                   1
    Test::More:                    0.41
    Devel::StackTrace:             0.9
    Data::Dumper:                  2
    Carp::Assert:                  0.17
    Time::Piece:                   1.07
    Log::Dispatch:                 2
    Class::Accessor:               0.17

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.12
